services:
  # 1. NGINX API Gateway (Publiczny punkt wejścia)
  - type: web
    name: lorely-gateway
    runtime: docker
    dockerfilePath: ./backend/nginx.dockerfile
    dockerContext: ./backend
    plan: free

  # 2. USER SERVICE
  - type: pserv
    name: user-service
    runtime: docker # <-- Zmieniono z 'env: docker'
    dockerfilePath: ./dockerfile
    dockerContext: ./backend/user-service
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lorely-db
          property: connectionString

  # 3. STORY SERVICE
  - type: pserv
    name: story-service
    runtime: docker
    dockerfilePath: ./dockerfile
    dockerContext: ./backend/story-service
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lorely-db
          property: connectionString

  # 4. CATALOG SERVICE
  - type: pserv
    name: catalog-service
    runtime: docker
    dockerfilePath: ./dockerfile
    dockerContext: ./backend/catalog-service
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lorely-db
          property: connectionString

  # 5. STORAGE SERVICE
  - type: pserv
    name: storage-service
    runtime: docker
    dockerfilePath: ./dockerfile
    dockerContext: ./backend/storage-service
    plan: free

# Automatyczne utworzenie darmowej bazy danych Postgres na Renderze
databases:
  - name: lorely-db
    plan: free
    databaseName: lorely
    user: vadosmik