services:
  # 1. NGINX (Publiczny punkt wejścia)
  - type: web
    name: lorely-gateway
    env: docker
    dockerfilePath: ./nginx.dockerfile # Musimy stworzyć ten plik, patrz Krok 2
    context: .
    plan: free
    port: 80 # Nginx nasłuchuje na porcie 80

  # 2. USER SERVICE (Prywatny)
  - type: pserv
    name: user-service
    env: docker
    dockerfilePath: ./user-service/dockerfile
    context: ./user-service
    plan: free

  # 3. STORY SERVICE (Prywatny)
  - type: pserv
    name: story-service
    env: docker
    dockerfilePath: ./story-service/dockerfile
    context: ./story-service
    plan: free

  # 4. CATALOG SERVICE (Prywatny)
  - type: pserv
    name: catalog-service
    env: docker
    dockerfilePath: ./catalog-service/dockerfile
    context: ./catalog-service
    plan: free

  # 5. STORAGE SERVICE (Prywatny)
  - type: pserv
    name: storage-service
    env: docker
    dockerfilePath: ./storage-service/dockerfile
    context: ./storage-service
    plan: free